### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by tukkek** [Zireael07/veins-of-the-earth-bearlib#1]
Hi! I had to add the libtcod.so file to the main directory to have the game work on Linux. I also had to install the package python-jsonpickle (`apt-get install python-jsonpickle`). 

I also had to install python2 since I didn't have it on my machine and then use `pip install bearlibterminal`.

You may want to add those instructions to an INSTALL.txt file.

Finally, for the sake of Linux users, you may want to add the following line as the first line of main.py: `#!/usr/bin/python2`. This will tell Linux installs to run the file with Python 2 if the user double clicks or tries to run with the terminal. Otherwise it may try to run Python 3 (or some other random program like BASH) and the game will fail. It won't affect the game otherwise since it's just a Python comment.

**Comment by tukkek** [comment]
The full apt-get command would be `apt-get install python2.7 python-pip python-jsonpickle`.

**Comment by Zireael07** [comment]
Closing as the missing file has been added and installation instructions provided as of https://github.com/Zireael07/veins-of-the-earth-bearlib/commit/ec9c26096609bddbe433c80993cd94fa7ddc4176
